// Code generated by protoc-gen-go. DO NOT EDIT.
// source: events.proto

/*
Package definitions is a generated protocol buffer package.

It is generated from these files:
	events.proto
	server.proto

It has these top-level messages:
	Event
	Heartbeat
	Alert
	EgressRequest
*/
package definitions

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Event struct {
	Timestamp  int64  `protobuf:"varint,1,opt,name=timestamp" json:"timestamp,omitempty"`
	Id         string `protobuf:"bytes,2,opt,name=id" json:"id,omitempty"`
	Deployment string `protobuf:"bytes,3,opt,name=deployment" json:"deployment,omitempty"`
	// Types that are valid to be assigned to Message:
	//	*Event_Heartbeat
	//	*Event_Alert
	Message isEvent_Message `protobuf_oneof:"message"`
}

func (m *Event) Reset()                    { *m = Event{} }
func (m *Event) String() string            { return proto.CompactTextString(m) }
func (*Event) ProtoMessage()               {}
func (*Event) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type isEvent_Message interface {
	isEvent_Message()
}

type Event_Heartbeat struct {
	Heartbeat *Heartbeat `protobuf:"bytes,4,opt,name=heartbeat,oneof"`
}
type Event_Alert struct {
	Alert *Alert `protobuf:"bytes,5,opt,name=alert,oneof"`
}

func (*Event_Heartbeat) isEvent_Message() {}
func (*Event_Alert) isEvent_Message()     {}

func (m *Event) GetMessage() isEvent_Message {
	if m != nil {
		return m.Message
	}
	return nil
}

func (m *Event) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *Event) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Event) GetDeployment() string {
	if m != nil {
		return m.Deployment
	}
	return ""
}

func (m *Event) GetHeartbeat() *Heartbeat {
	if x, ok := m.GetMessage().(*Event_Heartbeat); ok {
		return x.Heartbeat
	}
	return nil
}

func (m *Event) GetAlert() *Alert {
	if x, ok := m.GetMessage().(*Event_Alert); ok {
		return x.Alert
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*Event) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _Event_OneofMarshaler, _Event_OneofUnmarshaler, _Event_OneofSizer, []interface{}{
		(*Event_Heartbeat)(nil),
		(*Event_Alert)(nil),
	}
}

func _Event_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*Event)
	// message
	switch x := m.Message.(type) {
	case *Event_Heartbeat:
		b.EncodeVarint(4<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Heartbeat); err != nil {
			return err
		}
	case *Event_Alert:
		b.EncodeVarint(5<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Alert); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("Event.Message has unexpected type %T", x)
	}
	return nil
}

func _Event_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*Event)
	switch tag {
	case 4: // message.heartbeat
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(Heartbeat)
		err := b.DecodeMessage(msg)
		m.Message = &Event_Heartbeat{msg}
		return true, err
	case 5: // message.alert
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(Alert)
		err := b.DecodeMessage(msg)
		m.Message = &Event_Alert{msg}
		return true, err
	default:
		return false, nil
	}
}

func _Event_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*Event)
	// message
	switch x := m.Message.(type) {
	case *Event_Heartbeat:
		s := proto.Size(x.Heartbeat)
		n += proto.SizeVarint(4<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Event_Alert:
		s := proto.Size(x.Alert)
		n += proto.SizeVarint(5<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

type Heartbeat struct {
	AgentId    string              `protobuf:"bytes,1,opt,name=agent_id,json=agentId" json:"agent_id,omitempty"`
	Job        string              `protobuf:"bytes,2,opt,name=job" json:"job,omitempty"`
	Index      int32               `protobuf:"varint,3,opt,name=index" json:"index,omitempty"`
	InstanceId string              `protobuf:"bytes,4,opt,name=instance_id,json=instanceId" json:"instance_id,omitempty"`
	JobState   string              `protobuf:"bytes,5,opt,name=job_state,json=jobState" json:"job_state,omitempty"`
	Metrics    []*Heartbeat_Metric `protobuf:"bytes,6,rep,name=metrics" json:"metrics,omitempty"`
}

func (m *Heartbeat) Reset()                    { *m = Heartbeat{} }
func (m *Heartbeat) String() string            { return proto.CompactTextString(m) }
func (*Heartbeat) ProtoMessage()               {}
func (*Heartbeat) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Heartbeat) GetAgentId() string {
	if m != nil {
		return m.AgentId
	}
	return ""
}

func (m *Heartbeat) GetJob() string {
	if m != nil {
		return m.Job
	}
	return ""
}

func (m *Heartbeat) GetIndex() int32 {
	if m != nil {
		return m.Index
	}
	return 0
}

func (m *Heartbeat) GetInstanceId() string {
	if m != nil {
		return m.InstanceId
	}
	return ""
}

func (m *Heartbeat) GetJobState() string {
	if m != nil {
		return m.JobState
	}
	return ""
}

func (m *Heartbeat) GetMetrics() []*Heartbeat_Metric {
	if m != nil {
		return m.Metrics
	}
	return nil
}

type Heartbeat_Metric struct {
	Name      string            `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Value     float64           `protobuf:"fixed64,2,opt,name=value" json:"value,omitempty"`
	Timestamp int64             `protobuf:"varint,3,opt,name=timestamp" json:"timestamp,omitempty"`
	Tags      map[string]string `protobuf:"bytes,4,rep,name=tags" json:"tags,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
}

func (m *Heartbeat_Metric) Reset()                    { *m = Heartbeat_Metric{} }
func (m *Heartbeat_Metric) String() string            { return proto.CompactTextString(m) }
func (*Heartbeat_Metric) ProtoMessage()               {}
func (*Heartbeat_Metric) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1, 0} }

func (m *Heartbeat_Metric) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Heartbeat_Metric) GetValue() float64 {
	if m != nil {
		return m.Value
	}
	return 0
}

func (m *Heartbeat_Metric) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *Heartbeat_Metric) GetTags() map[string]string {
	if m != nil {
		return m.Tags
	}
	return nil
}

type Alert struct {
	Severity int32  `protobuf:"varint,1,opt,name=severity" json:"severity,omitempty"`
	Category string `protobuf:"bytes,2,opt,name=category" json:"category,omitempty"`
	Title    string `protobuf:"bytes,3,opt,name=title" json:"title,omitempty"`
	Summary  string `protobuf:"bytes,4,opt,name=summary" json:"summary,omitempty"`
	Source   string `protobuf:"bytes,5,opt,name=source" json:"source,omitempty"`
}

func (m *Alert) Reset()                    { *m = Alert{} }
func (m *Alert) String() string            { return proto.CompactTextString(m) }
func (*Alert) ProtoMessage()               {}
func (*Alert) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *Alert) GetSeverity() int32 {
	if m != nil {
		return m.Severity
	}
	return 0
}

func (m *Alert) GetCategory() string {
	if m != nil {
		return m.Category
	}
	return ""
}

func (m *Alert) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *Alert) GetSummary() string {
	if m != nil {
		return m.Summary
	}
	return ""
}

func (m *Alert) GetSource() string {
	if m != nil {
		return m.Source
	}
	return ""
}

func init() {
	proto.RegisterType((*Event)(nil), "definitions.Event")
	proto.RegisterType((*Heartbeat)(nil), "definitions.Heartbeat")
	proto.RegisterType((*Heartbeat_Metric)(nil), "definitions.Heartbeat.Metric")
	proto.RegisterType((*Alert)(nil), "definitions.Alert")
}

func init() { proto.RegisterFile("events.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 438 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x52, 0x4d, 0x8f, 0xd3, 0x30,
	0x10, 0xdd, 0x34, 0x4d, 0x5b, 0x4f, 0x11, 0x42, 0x23, 0xb4, 0x0a, 0xe5, 0xab, 0xea, 0x85, 0x8a,
	0x43, 0x0e, 0x8b, 0xc4, 0x22, 0x38, 0x81, 0xb4, 0x52, 0xf7, 0xc0, 0xc5, 0x70, 0x5f, 0x39, 0xcd,
	0x10, 0x5c, 0x1a, 0xa7, 0xb2, 0xa7, 0x15, 0xf9, 0x05, 0xdc, 0xf8, 0x55, 0x88, 0xdf, 0x85, 0xec,
	0x24, 0xdd, 0x2d, 0x42, 0xdc, 0xe6, 0xbd, 0xf9, 0xc8, 0x7b, 0x79, 0x86, 0x7b, 0x74, 0x20, 0xc3,
	0x2e, 0xdb, 0xd9, 0x9a, 0x6b, 0x9c, 0x16, 0xf4, 0x45, 0x1b, 0xcd, 0xba, 0x36, 0x6e, 0xf1, 0x2b,
	0x82, 0xe4, 0xca, 0x77, 0xf1, 0x09, 0x08, 0xd6, 0x15, 0x39, 0x56, 0xd5, 0x2e, 0x8d, 0xe6, 0xd1,
	0x32, 0x96, 0xb7, 0x04, 0xde, 0x87, 0x81, 0x2e, 0xd2, 0xc1, 0x3c, 0x5a, 0x0a, 0x39, 0xd0, 0x05,
	0x3e, 0x03, 0x28, 0x68, 0xb7, 0xad, 0x9b, 0x8a, 0x0c, 0xa7, 0x71, 0xe0, 0xef, 0x30, 0xf8, 0x1a,
	0xc4, 0x57, 0x52, 0x96, 0x73, 0x52, 0x9c, 0x0e, 0xe7, 0xd1, 0x72, 0x7a, 0x71, 0x9e, 0xdd, 0xf9,
	0x70, 0xb6, 0xea, 0xbb, 0xab, 0x33, 0x79, 0x3b, 0x8a, 0x2f, 0x21, 0x51, 0x5b, 0xb2, 0x9c, 0x26,
	0x61, 0x07, 0x4f, 0x76, 0xde, 0xfb, 0xce, 0xea, 0x4c, 0xb6, 0x23, 0x1f, 0x04, 0x8c, 0x2b, 0x72,
	0x4e, 0x95, 0xb4, 0xf8, 0x19, 0x83, 0x38, 0x5e, 0xc4, 0x47, 0x30, 0x51, 0x25, 0x19, 0xbe, 0xd1,
	0x45, 0x70, 0x22, 0xe4, 0x38, 0xe0, 0xeb, 0x02, 0x1f, 0x40, 0xbc, 0xa9, 0xf3, 0xce, 0x88, 0x2f,
	0xf1, 0x21, 0x24, 0xda, 0x14, 0xf4, 0x3d, 0x98, 0x48, 0x64, 0x0b, 0xf0, 0x39, 0x4c, 0xb5, 0x71,
	0xac, 0xcc, 0x9a, 0xfc, 0x95, 0x61, 0x6b, 0xb0, 0xa7, 0xae, 0x0b, 0x7c, 0x0c, 0x62, 0x53, 0xe7,
	0x37, 0x8e, 0x15, 0x53, 0x10, 0x2b, 0xe4, 0x64, 0x53, 0xe7, 0x9f, 0x3c, 0xc6, 0x4b, 0xaf, 0x8c,
	0xad, 0x5e, 0xbb, 0x74, 0x34, 0x8f, 0x97, 0xd3, 0x8b, 0xa7, 0xff, 0xf6, 0x9e, 0x7d, 0x0c, 0x53,
	0xb2, 0x9f, 0x9e, 0xfd, 0x8e, 0x60, 0xd4, 0x72, 0x88, 0x30, 0x34, 0xaa, 0xa2, 0xce, 0x40, 0xa8,
	0xbd, 0xd6, 0x83, 0xda, 0xee, 0x29, 0xe8, 0x8f, 0x64, 0x0b, 0x4e, 0x93, 0x8b, 0xff, 0x4e, 0xee,
	0x1d, 0x0c, 0x59, 0x95, 0x2e, 0x1d, 0x06, 0x21, 0x2f, 0xfe, 0x2b, 0x24, 0xfb, 0xac, 0x4a, 0x77,
	0x65, 0xd8, 0x36, 0x32, 0x2c, 0xcd, 0x2e, 0x41, 0x1c, 0x29, 0xff, 0xef, 0xbe, 0x51, 0xd3, 0x09,
	0xf2, 0xe5, 0xa9, 0x1e, 0xd1, 0xe9, 0x79, 0x3b, 0x78, 0x13, 0x2d, 0x7e, 0x44, 0x90, 0x84, 0xb8,
	0x70, 0x06, 0x13, 0x47, 0x07, 0xb2, 0x9a, 0xdb, 0xd5, 0x44, 0x1e, 0xb1, 0xef, 0xad, 0x15, 0x53,
	0x59, 0xdb, 0xa6, 0x3b, 0x71, 0xc4, 0xfe, 0x36, 0x6b, 0xde, 0x52, 0xf7, 0xb8, 0x5a, 0x80, 0x29,
	0x8c, 0xdd, 0xbe, 0xaa, 0x94, 0x6d, 0xba, 0x4c, 0x7a, 0x88, 0xe7, 0x30, 0x72, 0xf5, 0xde, 0xae,
	0xfb, 0x34, 0x3a, 0x94, 0x8f, 0xc2, 0xab, 0x7f, 0xf5, 0x27, 0x00, 0x00, 0xff, 0xff, 0x62, 0x01,
	0x31, 0x71, 0x05, 0x03, 0x00, 0x00,
}
